### ISSUE TITLE
Pagination on Section Page

### ISSUE THREAD

**Issue by schmoomsm** [archetyped/cornerstone#10]
Hi!

Love the plug-in. It made Wordpress work wonderfully with our site's (www.mco.org) diverse audiences, so big thanks!

We have issue that I've been unable to resolve: On Section pages, I can't get pagination to work.

We're using:
- Wordpress 4.4 english/Canada
- Hueman Theme - most recent (http://presscustomizr.com/hueman/)
- All plug-ins are up to date, including WP-PageNavi, which is recommended by the Hueman Theme, but the issue remains even without WP-PageNavi on.

I've attached my revised loop code, which appears on theme's Child Menu Template 
[HUE-CORNERSTONE.txt](https://github.com/archetyped/cornerstone/files/76036/HUE-CORNERSTONE.txt). Most of the code comes from content-standard.php of the theme, too. I'm not a developer by any stretch.

If you'd like to see how section pages display, look at http://www.mco.org/wordpress/autocross-news/

There are many, many more posts in that section that are accessible only through search.

Again, many thanks for the plug-in. It has been a life-saver for us.

Thanks in advance and all the best for 2016!

Naresh Debidin
Motorsport Club of Ottawa

**Comment by archetyped** [comment]
Thanks for the report.  I am looking into this.

**Comment by schmoomsm** [comment]
Hi,

Wondering if you've made any progress? Thx!

**Comment by IkeTen** [comment]
Same issue with generatepress theme. Am using this [here.](https://gist.github.com/IkeTen/3a1b438908fae310e74c94b74cd0f784#file-sections-php)

**Comment by archetyped** [comment]
Here is an example using WP's `paginate_links()`.  You can further customize the pagination output using `paginate_links()` other parameters ([documentation](https://codex.wordpress.org/Function_Reference/paginate_links)).

```php

echo paginate_links( array(
	'format' => 'page/%#%/',
	'total' => cnr_children_max_num_pages(),
	'current' => get_query_var('paged')
) );

```
