### ISSUE TITLE
Sections are not populated to permalink

### ISSUE THREAD

**Issue by netxecute** [archetyped/cornerstone#11]
Plugin works fine for older posts - when I am trying to create a new post, I select a section and then type a post name.  The only thing populated to the permalink is the post name.  I have permalinks set to structured.  I have also attempted changing and saving back to structured with no effect.

Latest wordpress (4.4.1)
Latest CNR (0.7.3)
Only plugin activated
Tested with several themes including 2015 and 2016

If you want the URL, I will need to provide you temporary admin access, please contact me directly if that is required.
I usually just use Chrome.  I really don't feel this is a browser issue at all.
Plugins installed.  Tested with only Cornerstone activated.
AdRotate
Version 3.7.4.3

AG Custom Admin
Version 1.4.8.2

Author Category
Version 0.8

bbPress
Version 2.5.8

BlackBox
Version 0.1.3

Cornerstone
Version 0.7.3

Event Calendar / Scheduler
Version 3.0

Events Manager
Version 5.6.1

Link Manager
Version 0.1-beta

Map Categories to Pages
Version 1.3.2

Members
Version 0.2.5

One-Click Child Theme
Version 1.6

Quick Page/Post Redirect Plugin
Version 5.1.4

RSS Multi Importer
Version 3.15

User Switching
Version 1.0.8

Visual Form Builder
Version 2.8.6

Widget Builder
Version 1.6.2

Widget Context
Version 0.7.2

**Comment by archetyped** [comment]
Hi, just to confirm, are you saying that add structured permalink (i.e. `/section-name/post-name/`) is not being used for a post once it has been saved?

If so, what is the permalink of the saved post?

**Comment by netxecute** [comment]
Usually you can see the permalink as soon as I've selected a section and written a post title. 
Now all I get is http://domain.com/post-title-as-permalink
Does that explain? 
T

-------- Original message --------

**Comment by netxecute** [comment]
Do you need anything else?

**Comment by netxecute** [comment]
I know this is a free plugin but would love to know what options I have.  It will be a pig to have to rebuild the site using a different or no plugin to provide this functionality.  Is there anything I can do to help you?  Do you have any tips for where to look or tests to try?

**Comment by archetyped** [comment]
Hi, it appears that WordPress itself only dynamically updates the permalink preview when a title is set for a new post or when the preview is edited directly.  Other than that, the preview is updated when the post is saved.

A future update of CNR may enhance the permalink preview to update whenever the section is changed, but currently it does not affect WordPress standard behavior.
