### ISSUE TITLE
Posts Page

### ISSUE THREAD

**Issue by shaneparsons** [archetyped/cornerstone#12]
First off, thanks for the plugin.. seems promising so far!

I'm having an issue where posts that are only supposed to be displayed on my 'work' page are showing on my 'news' page. I have a feeling this is because my 'news' page is set as my 'Posts Page' but I wanted to verify it with you guys.

Do I need to disable the 'Posts Page' linkage and just have my 'news' page formatted as a standard page?

**Comment by archetyped** [comment]
Hi, yes, posts are still retrieved by standard WordPress queries even when added to sections, so they will be included on the Posts Page.  With Cornerstone, you can disable the Posts page functionality and simply assign news posts to the news section.
