### ISSUE TITLE
cornerstone always want to connect to wordpress admin

### ISSUE THREAD

**Issue by jef94100** [archetyped/cornerstone#13]
When i want to change a page in my word press blog, I press "Pages", then "Edit with Cornerstone" and instead of opening the page like before, now it ask me to enter admin and password of may /wp-admin page, and when i do so, it goes directly to the website and not to the cornerstone page... any idea of what is happening ??? At the beginning all was ok, all the rest is ok and the problem is only when i try to use cornerstone. 

Thanks for your help

**Comment by archetyped** [comment]
Hi, it appears you may be referring to a different plugin.  This plugin does not have an "Edit with Cornerstone" button.  A link to the developer's website is generally located next to the plugin on the plugins admin page of your site.
