### ISSUE TITLE
Editing with cornerstone not an option on all pages 

### ISSUE THREAD

**Issue by rmerhi2** [archetyped/cornerstone#14]
When I click options on my menu such as "About me", the page pops up but then the option to edit with cornerstone is not available at the top left corner. 

Therefore, I went directly to pages to attempt to pull it up there. However, the page was not listed there.I don't know why it is not being recognized as a page. The thing is none of my pages are being recognized as pages and the only ones that are pages that I create that are linked up with the menu options. Therefore, the only way that people would be able to access it is if they were to type in that exact URL- which is not going to happen. 

When I tried to create the page by entering in the same URL as the About me page, it created it, but it not only was a different page, but I still could not edit with cornerstone. I'm beyond confused because it seemed for everyone else that I have talked to, theirs just worked.

**Comment by archetyped** [comment]
Hi, it sounds like you may be referring to a different plugin.  A link to the developer's website is included next to the plugin in your site's list of plugins.
