### ISSUE TITLE
Problems with adding sections

### ISSUE THREAD

**Issue by leelee24** [archetyped/cornerstone#15]
I have tried to create new sections for a template I have just purchased however when I try to add new sections they do not appear in the workspace to the right. As a result I cannot add any elements to the page. How do I fix this problem?

**Comment by archetyped** [comment]
Hi, can you please clarify the problem you're experiencing?  Cornerstone uses standard WordPress pages as sections that you can add posts to.  Also, I'm not sure what "workspace to the right" you're referring to.

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity.  If you are still experiencing an issue with Cornerstone, please provide the requested details and I would be glad to take a look.
