### ISSUE TITLE
Cannot delete

### ISSUE THREAD

**Issue by LilyWe** [archetyped/cornerstone#16]
After I create an element using Cornerstone, but want to delete it, I click on delete and when I click on 'yep' or 'nope' nothing happens.  It freezes up.  It was working but stopped yesterday, for some reason.
I have purchased the x theme, but am using it on another wordpress theme, since it's such a great backend builder.

Our website, www.westtownentertainment.com is currently in maintenance mode.
Cornerstone ver 1.1.3
Using Safari

Thanks,
Lily

**Comment by archetyped** [comment]
Hi, it sounds like you're referring to a different plugin.  You can usually find a link to the plugin's official website below the plugin's name on the plugin admin page of your site.
