### ISSUE TITLE
Can not Delete

### ISSUE THREAD

**Issue by melmicah** [archetyped/cornerstone#17]
the delete function in my cornerstone is not working.

**Comment by archetyped** [comment]
Hi, Cornerstone does not have a delete function.  Can you please provide more details on the issue you're experiencing?

Thanks.

**Comment by johndeu** [comment]
I'm having the exact same issue on all Browsers in latest release of CornerStone. Using the X-Theme, and the included support for Cornerstone. Unable to delete anything in the UI. I can click delete and the left black slider comes out with the confirmation dialog of Yep and Nope but i cant click on either of them. No action.  No keyboard navigation shortcut either to force it to delete. 
![cornerstone delete issue](https://cloud.githubusercontent.com/assets/39712/14796710/95e8101e-0ae3-11e6-89ab-189fe7cd8f39.png)

**Comment by archetyped** [comment]
Hi, it sounds like you may be referring to a different plugin, as the functionality you describe is not part of Cornerstone.

You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page.

**Comment by rachellwalters** [comment]
I am having this same issue, and this is most certainly a function of cornerstone, as the screenshot above is exactly like the one I am including below, and I have included the tab at top, which clearly shows the title tag of Cornerstone. Please fix this issue, as I attempted to add a code block to the site, which rendered as text, and now appears as a grey box which I cannot move. 
<img width="454" alt="screen shot 2016-05-19 at 10 41 35 pm" src="https://cloud.githubusercontent.com/assets/19482834/15415803/535b98ae-1e13-11e6-9a20-6cd4958ec916.png">
