### ISSUE TITLE
Cannot Delete

### ISSUE THREAD

**Issue by rachellwalters** [archetyped/cornerstone#18]
Searching the history, I see this has been an issue for a few other people, and their issues were closed and marked invalid, not resolved. Please see screenshot below, which includes the title tag of the page, "Cornerstone" this is part of your page builder.

I attempted to insert a code block, which rendered as text, and now has left a grey bar across the hero image of my site. I am unable to move this to another section, or drop it to the bottom as at least a temporary solution.

Please fix your page builder, write now it is a page wrecker. Looking forward to a swift resolution.

<img width="454" alt="screen shot 2016-05-19 at 10 41 35 pm" src="https://cloud.githubusercontent.com/assets/19482834/15415875/d02ffb0e-1e13-11e6-91d4-0f04d2e60c4f.png">

**Comment by archetyped** [comment]
Hi, this is a forum for the [Cornerstone](https://wordpress.org/plugins/cornerstone/ "Cornerstone") plugin in WordPress' official plugin directory.  It is not a page builder plugin.

Unfortunately, there is nothing stopping anyone else from also naming their plugin "Cornerstone" as well, so I understand your confusion.  You should be able to find a link to the plugin's actual home page below the plugin's name on your site's plugin admin page, where you can hopefully locate the proper channels for getting support for that plugin.
