### ISSUE TITLE
installing cornerstone

### ISSUE THREAD

**Issue by dwellslit** [archetyped/cornerstone#19]
I am not a technical person.  I have downloaded a website theme that uses cornerstone.  When I try to active it, I get the following error: 500 - Internal server error.  There is a problem with the resource you are looking for, and it cannot be displayed.  Simple responses are very much appreciated.

**Comment by archetyped** [comment]
Hi, please provide a link to the theme that includes Cornerstone and would be glad to take a look into it.

Also, you can install Cornerstone directly via [WordPress' plugin directory](https://wordpress.org/plugins/cornerstone/).

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with Cornerstone, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
