### ISSUE TITLE
Cornerstone Tab Not Visible in Editor

### ISSUE THREAD

**Issue by korneld** [archetyped/cornerstone#20]
Hi. Just installed Cornerstone. It is activated, but the tab is not showing up in next to Visual and Text when editing either a post or a page. I have the very latest version of WP and Cornerstone. The theme is Hueman. I tried it with all other plugins deactivated, but no luck.

**Comment by archetyped** [comment]
Hi, Cornerstone does not add any tabs to the post/page editor.  It sounds like you may be referring to a different plugin that uses the same name.

You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
