### ISSUE TITLE
Cornerstone Not Saving

### ISSUE THREAD

**Issue by kylecrawley** [archetyped/cornerstone#21]
When I make a correction to a page with Cornerstone it does not save. The green ribbon that displays that a save has been made shows up, but the content that is changed never saves. Why won't Cornerstone allow save changes made to our webpages?

**Comment by archetyped** [comment]
Hi, can you provide more details on what you mean by "make a correction to a page with Cornerstone"?  Perhaps a screenshot will make things clearer?  It sounds like you may be referring to a different plugin.  You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with Cornerstone, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.

**Comment by kylecrawley** [comment]
Hello,

I'm still having trouble making edits to my website. For some reason I
can't edit the main home page, but I can edit every other page on the site.
There really isn't much I can screen shot. Because when I hit the save
button at the bottom left cornerstone indicates that the changes have been
changed.




*Kyle Crawley*
*Executive Director                  *
*Stepping Stones of the Roaring Fork Valley*
*1010 Garfield Ave, Carbondale CO 81623*
*720.207.7646* l *www.steppingstonesrfv.org*
<http://www.steppingstonesrfv.org/> l
<https://www.facebook.com/profile.php?id=100009981242016&fref=ts>

**Comment by archetyped** [comment]
Hi, Cornerstone does not display any notes/alerts when a post/page has been saved or changed.  It leaves this to WordPress itself.

As previously noted, it sounds like you are referring to a different plugin.  You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.  

However, if you can provide a screenshot of the visual elements you are referring to (e.g. "green ribbon that displays that a save has been made", "when I hit the save button at the bottom left cornerstone indicates that the changes have been changed", etc.), it would greatly help to clarify the issue you are experiencing.

Thanks.

**Comment by kylecrawley** [comment]
Here are some screens shots of the problem I'm experiencing. The two
pictures below show how I get conflicting information when I save changes
to the website. The green ribbon is displayed every time I save changes,
which is normally what happens every time I save a new change. The changes
never save and the wordpress dashboard at the bottom says "you have not
saved any changes!"

For some reason I can make edits using cornerstone on every other page, but
our home page.



[image: Inline image 2]



[image: Inline image 1]




*Kyle Crawley*
*Executive Director                  *
*Stepping Stones of the Roaring Fork Valley*
*1010 Garfield Ave, Carbondale CO 81623*
*720.207.7646* l *www.steppingstonesrfv.org*
<http://www.steppingstonesrfv.org/> l
<https://www.facebook.com/profile.php?id=100009981242016&fref=ts>

**Comment by archetyped** [comment]
Hi, it looks like images included in email replies are not supported.  Please post your screenshots by visiting the ticket's page in your web-browser and I will take a closer look.

Thanks.

**Comment by kylecrawley** [comment]
*Kyle Crawley*
*Executive Director                  *
*Stepping Stones of the Roaring Fork Valley*
*1010 Garfield Ave, Carbondale CO 81623*
*720.207.7646* l *www.steppingstonesrfv.org*
<http://www.steppingstonesrfv.org/> l
<https://www.facebook.com/profile.php?id=100009981242016&fref=ts>

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with Cornerstone, please provide the previously-requested details and I would be glad to reopen the ticket and take another look.

**Comment by Johanne450** [comment]
I'm having the same problem, and I opened a ticket with the developper for the theme I'm using.  They replied last night, saying that they made some changes on blog posts thru Cornerstone to test the problem I had described and that those changes were saved properly (they had attached screenshots).  

Since I had never added Cornerstone elements to blog posts (only to pages), much less edit them after publication, this allowed me to realize that the trouble occurred only on pages (static pages, not blog posts) where I had added Creative CTA modules, which I used to enter photo credits for the backgrounds used on most of my pages.  That's why any change I made to any part of a page could not be saved; I have Creative CTAs almost everywhere!

I can make changes to the text in the modules thru the Text view of the Wordpress editor, and they get saved just fine, but of course, when I go back to Cornerstone, all those changes are gone again. 

This prevents me from simply removing the defective Creative CTA modules from my pages and get rid of the problem, because it has to be done thru Cornerstone but it won't let me save any change...  

I'm always back to square one.  Can you help?

**Comment by archetyped** [comment]
Hi @Johanne450, Hi, this is the support forum for [the Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that uses the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.

**Comment by Johanne450** [comment]
Oops! Sorry, and thank you for taking the time to reply.  I was finally able to solve my problem anyway.  

The plugin came as part of a theme I purchased, and unfortunately, de theme developper was not able to help me.  It took me several days, but I found a solution.  So everything is fine now.  

Thanks again!
