### ISSUE TITLE
Duplicating a page with Cornerstone enabled doesn't work

### ISSUE THREAD

**Issue by scottybo** [archetyped/cornerstone#22]
As part of our design workflow we like to create a template page (e.g. a "service" page) and then we'll duplicate that page 10 times if there are 10 services.

We use the plugin "Duplicate Post": https://wordpress.org/plugins/duplicate-post/ to achieve this.

However, whenever we try to duplicate posts/pages that have Cornerstone enabled, the page seems to "forget" that it is a cornerstone page and we're left with a blank page.

It would be great if Cornerstone played nicely when duplicating, or you guys introduced a quick and easy way to duplicate a post/page or copy a post/page to a new draft

**Comment by archetyped** [comment]
Hi, can you provide more details on what you mean by "cornerstone page"?  Cornerstone does not affect pages (only posts).

**Comment by scottybo** [comment]
Sorry for the slow response and for the incorrect terminology! I meant post when saying page - i.e. when trying to duplicate a post, all the cornerstone layout items are lost

**Comment by scottybo** [comment]
Seems to be working with the latest version of duplicate post!
