### ISSUE TITLE
Cornerstone, reverse posts on page

### ISSUE THREAD

**Issue by paytonbissell** [archetyped/cornerstone#23]
Your plugin is awesome, works wonderfully. I need to reverse the order of the posts on ONE page. If that is impossible, I'd like to reverse the order for all pages. I have gingerly poked around the code, and played with loops, but I can't seem to make it work right. Can you offer any advice on:
(1) making a reverse order post loop, and 
(2) logic to control the order by page?
THANK YOU!

**Comment by archetyped** [comment]
Hi, apologies for the delayed response.  Reversing post order not currently possible, but I'll keep it in mind for a future update.

Thanks!
