### ISSUE TITLE
Error when attempting to activate Cornerstone

### ISSUE THREAD

**Issue by gpi56ar** [archetyped/cornerstone#24]
Warning: require_once(includes/utility/plugin-base.php): failed to open stream: No such file or directory in G:\PleskVhosts\vhigroup.com.au\build.vgourmet.com.au\wordpress\wp-content\plugins\cornerstone\cornerstone.php on line 20

Fatal error: require_once(): Failed opening required 'includes/utility/plugin-base.php' (include_path='.;.\includes;.\pear') in G:\PleskVhosts\vhigroup.com.au\build.vgourmet.com.au\wordpress\wp-content\plugins\cornerstone\cornerstone.php on line 20

Can you advise?
I have removed and reinstalled multiple times

**Comment by archetyped** [comment]
Hi, it appears that you are using a different plugin that uses the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
