### ISSUE TITLE
Unable to delete in Cornerstone 

### ISSUE THREAD

**Issue by redefined723** [archetyped/cornerstone#25]
I haven't be able to delete any elements in Cornerstone this week. Example: I added a feature box to a column just now as a test. When I attempt to delete it, nothing happens. In order to get rid of the element, I have to refresh the whole page and start over from whenever it was last saved. 

Any suggestions on how to fix this? 

<img width="999" alt="screen shot 2017-02-07 at 4 02 56 pm" src="https://cloud.githubusercontent.com/assets/25621875/22711363/ec701cda-ed4e-11e6-9edb-2fa67d580fa9.png">

**Comment by archetyped** [comment]
Hi @redefined723, I see you closed this ticket, so perhaps you know this already, but this is the support forum for [the Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that uses the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
