### ISSUE TITLE
Videos Will Not Unpause

### ISSUE THREAD

**Issue by ansley** [archetyped/cornerstone#26]
Hello! I am using your Cornerstone plugin this website http://www.masterymomentseekers.com/ for content behind a membership wall (please get in touch with me to get login info if you need to see behind the scenes) and the strangest thing: videos entered through Cornerstone can be paused, but then they cannot be unpaused. I have tested across multiple browsers, I have disabled all other plugins, and I have also tried embedding the same video on a page without cornerstone with all other plugins enabled and that works just fine.

Please let me know what I can do to assist you in helping me solve this strange glitch. Thanks!

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress’ official plugin directory](https://wordpress.org/plugins/cornerstone/).  It appears that you are using a different plugin that uses the same name, as this plugin does not have any video-specific functionality.

You should be able to find a link to the plugin’s official home page below the plugin’s name on your site’s plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
