### ISSUE TITLE
Can't delete sections (when popout prompt appears from left side of screen)

### ISSUE THREAD

**Issue by trainwithnoname** [archetyped/cornerstone#27]
Hello there- 
I am setting up a webpage using Cornerstone and have hit an impasse. I cannot delete sections. For example, I use the template feature and select a section to add to my site page. But after I add it, I decide I don't like it and want to delete it. When I click the small garbage can icon by the section (see screenshot 2), a column on the left hand side of the screen pops out and asks "Are you sure you want to delete this row along with all it's contents?" along with an orange button that says "Yep" and a grey button that says "nope". Neither button responds to being clicked. Which is preventing me from confirming the deletion of the section. 
I finally found another way to save the page, via the link along the bottom of the page. Is there another way to delete sections, or way to fix this so it works properly?

Thank you
![cornerstone error](https://cloud.githubusercontent.com/assets/25809779/23006338/27a69fbe-f3cf-11e6-933f-56bf8c9e2b03.JPG)
![cornerstone error 2](https://cloud.githubusercontent.com/assets/25809779/23006342/2a80bdaa-f3cf-11e6-9773-36cee46daac5.JPG)

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that uses the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
