### ISSUE TITLE
Cornerstone Installation

### ISSUE THREAD

**Issue by daria-elium** [archetyped/cornerstone#28]
Hello,

I've downloaded Cornerstone plugin for Wordpress 4.7.3, and activated it, but when I open Page editor, no button appears. Is there an installation step I'm missing?

Thanks

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that uses the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
