### ISSUE TITLE
No links in title of posts in sections

### ISSUE THREAD

**Issue by twhite96** [archetyped/cornerstone#29]
I got the sections up and working but the titles of posts in those sections aren't linked to the post. So if I go to the App Review section, there is one post, but I can't click on it to take me to the blog post. See: https://thatmacnerd.com/app-reviews/.

I have a lot of plugins installed. But that isn't the issue.

I am on Chrome on macOS, latest of everything.

I also added already written content to a section. I don't know if I add new content to a section, if you will be able to click that post in a section and then be taken to that post or not.

Am I doing something wrong?

**Comment by archetyped** [comment]
Hi, just like normal posts, a section's posts are displayed exactly according to the loop used to output the posts.  This means you can use any of WordPress' template tags ([see official documentation here](https://codex.wordpress.org/Template_Tags)) to generate the output you desire.

For example, using WordPress' `the_permalink()` template tag ([documentation & examples here](https://codex.wordpress.org/Function_Reference/the_permalink)) will allow you to place a link to a post's own URL anywhere you want to (using the title, a "read more" link after the excerpt, etc.).
