### ISSUE TITLE
RSS for sections? Not clear how to do that.

### ISSUE THREAD

**Issue by twhite96** [archetyped/cornerstone#30]
Documentation for this is really sparse. Your website doesn't have a lot of direction either.

How do I add RSS feeds to each section?

**Comment by archetyped** [comment]
Hi, RSS feed links can be generated using Cornerstone's `cnr_the_feed_links()` function.  See the `functions.php` file in Cornerstone's plugin folder for other available functions/template tags.

**Comment by twhite96** [comment]
If you're going to do this, how about some better docs? How are the feed links generated? What URL will they use? It's a great, open source plugin but it is hard to use.

**Comment by twhite96** [comment]
Also the feed links are actually links to different posts in a section, which isn't very logical. I would like a feed for the whole *page*. How do I do that?

**Comment by archetyped** [comment]
Hi, I'm not sure what you mean by "the whole page".  An RSS feed is used to show when there are updates on a site (i.e. new posts).  As such, section-specific RSS feeds include new posts as they are added to a section.  This allows visitors to subscribe to such a feed and see when there are new posts added to a specific section.

**Comment by twhite96** [comment]
Okay. Thanks.
