### ISSUE TITLE
Cornerstone tab not showing up

### ISSUE THREAD

**Issue by thenilo** [archetyped/cornerstone#31]
Hi, 

I have downloaded cornerstone plugin and have installed it on my current website theme "Boston". 
Cornerstone is already installed and activated on my website, however, I cannot see the "cornerstone" tab whenever I try creating a new post or page. What should I do?

I have already tried deleting it and re-installing again, but that did not solve the problem.

Thanks,

**Comment by archetyped** [comment]
Hi, this is the support forum for [the Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that uses the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
