### ISSUE TITLE
The content has been modified outside of Cornerstone 

### ISSUE THREAD

**Issue by hetalpatel2311** [archetyped/cornerstone#32]
After site migration ,when I am editing page  
Hold up! The content has been modified outside of Cornerstone. Editing in Cornerstone will replace the current content. Do you wish to continue?

error message comes

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may have the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
