### ISSUE TITLE
Creating A Link In single.php That Goes To Post's Parent Section Page

### ISSUE THREAD

**Issue by trowell777** [archetyped/cornerstone#33]
Hello Archetyped,  Thank you for creating Cornerstone it really expands the capability of Wordpress to a website structure that I have been searching for.  Well done!
I am a newbie to Wordpress and PHP so I am fumbling my way around as I learn.
I would like to create a link at the bottom of each post that takes the reader back to the post's parent cornerstone section (page).  Would it be possible to put something in the Single Post template (single.php) file?

As an example if there were pages  pets:dogs and a post titled "pugs_snore" in section "dogs".  Could some code automatically create some text "Return to dogs" and link to the "dogs" page at the bottom of the "pugs_snore" post?

I see some functions called "cnr_get_featured", "get_path", and "get_parents". Would any of these work?
Thanks, Tim

**Comment by archetyped** [comment]
CNR's `cnr_get_the_section()` template tag retrieves data for a post's section (e.g. the section's ID).

Usage example (outputting link to a post's section):

```php
// Retrieve section ID.
$section_id = cnr_get_the_section('ID');

// Output section link.
if ( ! empty( $section_id ) ) {
	the_permalink( $section_id );
}
```
