### ISSUE TITLE
Cornerstone Tab Not visible in Wordpress page edit

### ISSUE THREAD

**Issue by ellejay78** [archetyped/cornerstone#34]
Hi,
Followed installation instructions and i still don't see the tab for cornerstone beside the visual and text tab.  Any suggestions

Thanks,
Laura

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
