### ISSUE TITLE
Posts are available by different URLs 

### ISSUE THREAD

**Issue by vdmktv** [archetyped/cornerstone#35]
Hi, 

For example, posts from your website are available by URLs with sections and without them:
https://archetyped.com/know/cornerstone-using-custom-field-data-in-wordpress/
https://archetyped.com/cornerstone-using-custom-field-data-in-wordpress/

I'm also having this issue on my site. How to fix it?

**Comment by archetyped** [comment]
Hi, the reason for this is that WordPress only looks at the slug (e.g. `cornerstone-using-custom-field-data-in-wordpress`) when determining what post to load, so the section or other path details are not required for the correct post to be loaded.

However, with Cornerstone installed, using WordPress' built-in functions such as `the_permalink()`, etc. should generate the correct section-based URL for a post.  If this is not happening, please provide some details regarding how you are generating URLs and I would be glad to take a look.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with Cornerstone, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
