### ISSUE TITLE
Classic Features List Glitch

### ISSUE THREAD

**Issue by ontrackthemes** [archetyped/cornerstone#36]
Our site's icons and text are no longer aligned and we cannot figure out the adjustment to fix it.

See "OUR PROCESS" here: ontrackthemes.com

The various icons should be aligned with the text.

**Comment by archetyped** [comment]
Hi, it appears that you are using a different plugin that may be using the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
