### ISSUE TITLE
Cornerstone crashing website

### ISSUE THREAD

**Issue by teameltaco** [archetyped/cornerstone#37]
Hi,

We are in the process of moving our hosting to a cloud service with United Hosting. We are in initial testing and have found that Cornerstone is crashing the site when activated. It is a WordPress site running X-Theme. All is working fine on the existing hosting account.

**Comment by archetyped** [comment]
Hi, this is the support forum for [the Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/ "Cornerstone").

It sounds like you are using a different plugin that may be using the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.

If you are indeed experiencing an issue with the Cornerstone plugin installed from WordPress' official plugin directory, please provide additional details about any error messages you are receiving and I would be glad to take a look.

Thanks.
