### ISSUE TITLE
Updated Cornerstone and Now it's Not Working

### ISSUE THREAD

**Issue by ajauntwithjoy** [archetyped/cornerstone#38]
I updated my Cornerstone in Wordpress.org and now even though it's activated as a plugin, when I hover over my blog posts and pages, "Edit with Cornerstone" doesn't appear anymore and all of my posts I had created and edited in Cornerstone are now just in the regular editor and not in cornerstone format. 

I deactivated, deleted, and reinstalled and reactivated but it's still the same issue.

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
