### ISSUE TITLE
Can't update Cornerstone

### ISSUE THREAD

**Issue by allynmedia** [archetyped/cornerstone#39]
Cornerstone is not letting me delete anything so I tried updating but I am getting an error, "Update Failed: Update package not available." 

http://www.republicofhumanity.org/

The main problem that I need to solve is that the social wall stopped working on the homepage and I was trying to delete it to re-add it but I can't delete it. If there is a better solution to fixing this, I am all ears!

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).  

It appears that you are using a different plugin that may be using the same name as Cornerstone does not have a "social wall" feature.

You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
