### ISSUE TITLE
Retrieve posts from sections

### ISSUE THREAD

**Issue by M-Brico** [archetyped/cornerstone#4]
Is it possible to retrieve posts from a particular section? I have setup pages and added posts to sections. But would like to have latest posts from each section on the homepage. Is this possible?

**Comment by archetyped** [comment]
Hi, you can use [WordPress' built-in `get_children()`](https://codex.wordpress.org/Function_Reference/get_children) to get a section's posts.  For more specific results, you can use the following parameter values:

* `post_parent`: The section ID
* `post_type`: `'post'`
