### ISSUE TITLE
Can't delete sections in Cornerstone

### ISSUE THREAD

**Issue by gabgirl1047** [archetyped/cornerstone#40]
Hello. I am attempting to edit a website that was designed by WordPress and Cornerstone. However, I am unable to delete sections on pages that are already published. Both my WordPress and Cornerstone are updated to the newest version.

**Comment by archetyped** [comment]
Hi, this is the support forum for the Cornerstone plugin in WordPress' official plugin directory.

It appears that you are using a different plugin that may be using the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.

**Comment by allynmedia** [comment]
I am having the same problem and this is were the plugin info takes me.
<img width="918" alt="screen shot 2018-08-03 at 10 31 34 am" src="https://user-images.githubusercontent.com/41276099/43651634-88ba9d36-9708-11e8-8f44-f39d633be81b.png">

It says that this is the plugin created by archetyped. It won't let me delete anything and it won't let me update it.

**Comment by archetyped** [comment]
Perhaps you are mixing up Cornerstone's functionality with another plugin you have installed then?  Cornerstone does not have any functionality to "delete sections on pages".

If I have misunderstood what you are trying to do with Cornerstone, please provide additional details and I would be glad to take another look.

**Comment by allynmedia** [comment]
After looking closer - it looks like Wordpress has an error. You may want
to report it, it may be the cause of a lot of people complaining about this
same issue.

This website only has one plugin called cornerstone installed and your site
is where it takes you when you are looking for support.









*Jessica Ring Moore Allyn Media 3838 Oak Lawn Avenue, Suite 400 Dallas, TX
75219 214-871-7723 AllynMedia.com *
