### ISSUE TITLE
collapsed menu icon does not work with cornerstone update 3.2.5

### ISSUE THREAD

**Issue by snegrin** [archetyped/cornerstone#41]
After performing the update, the collapsed menu icon for my site (www.siupinghealing.com) doesn't respond on any browser including my iPhone.  I have since rolled the update back. 
My version of cnr is 2.1.7. 

Please help. Thank you!

**Comment by archetyped** [comment]
Hi, this is the support forum for [the Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
