### ISSUE TITLE
Sidebar widget is not appears in the editor if using gutenberg

### ISSUE THREAD

**Issue by mewatashiakumoi** [archetyped/cornerstone#42]
Hello Archetyped,
The plugin seems working good on latest wp! But there's an issue where if i use the new wp editor 'gutenberg', the sidebar widget to choose the section is not appearing there

Easily mitigate by disabling gutenberg, but can you help check and fix it?

**Comment by archetyped** [comment]
Thanks for the report.  I've added it to the to-do list and will look into it.

**Comment by mewatashiakumoi** [comment]
Thanks man, looking forward to it! 😄

**Comment by archetyped** [comment]
Updates to Gutenberg appear to have restored metabox compatibility.  If you are still experiencing this issue, please post and update and I would be glad to take another look.
