### ISSUE TITLE
PHP 7.2 supported?

### ISSUE THREAD

**Issue by tinatenatean** [archetyped/cornerstone#43]
WPEngine.com is forcing users to upgrade to PHP version 7.2.  Does this plugin support 7.2?

**Comment by archetyped** [comment]
Hi, there are no known issues with PHP 7.2, though testing your particular site in a staging environment is always recommended when making changes, especially when updating core software such as PHP.

Please feel free to [create a new ticket](https://github.com/archetyped/cornerstone/wiki/Reporting-Issues) if you do encounter any issues with Cornerstone.
