### ISSUE TITLE
JetPack

### ISSUE THREAD

**Issue by ExtractsCollectionSA** [archetyped/cornerstone#45]
We recently added WooCommerce Plug In - which works with JetPack Plug In - and when I activate Jet Pack I am not able to edit our site with Cornerstone. 

we have the X Theme -
I get to the editor page, https://extractscollection.com/wp-admin/customize.php?return=https%3A%2F%2Fwordpress.com%2Fplugins%2Fcornerstone%2Fextractscollection.com 
but then when wanting to edit it just does nothing -  https://extractscollection.com/x/#/options 

As soon as I disable jet pack everything works fine - but we need jet pack to work with the phone app. 

please assist. 

<img width="1433" alt="Screenshot 2019-03-18 at 10 54 04" src="https://user-images.githubusercontent.com/48673456/54518108-32dab380-496c-11e9-8a36-f74422ee0236.png">
<img width="1440" alt="Screenshot 2019-03-18 at 10 54 15" src="https://user-images.githubusercontent.com/48673456/54518109-33734a00-496c-11e9-9cc1-a9fdafeccaa9.png">

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name. You should be able to find a link to the plugin's official home page below the plugin's name on your site's plugin admin page. You may also be able to find information on getting support via the site where you downloaded/purchased the plugin/theme.

Thanks.
