### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ClaudiaCastilloPhotography** [archetyped/cornerstone#48]
I just purchased Theme X and transferred my web to new hosting and I installed Theme X, all the plugins are activated except Cornerstone.
It tells me I need to activate it and when I do, I get this error:

Fatal error: Cannot redeclare cs_generate_data_attributes() (previously declared in /homepages/10/d865529732/htdocs/app866424572/wp-content/plugins/tco-video-lock/functions/includes/cs/helpers.php:4) in /homepages/10/d865529732/htdocs/app866424572/wp-content/plugins/cornerstone/includes/utility/helpers.php on line 295

I have no clue how to fix it

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name, as the details you provided do not match this plugin. The plugin you are using may include support information on the plugin's own admin page.  You may also be able to find support information via the site where you downloaded/purchased the plugin.
