### ISSUE TITLE
My website crashes when I try to activate my cornerstone plugin

### ISSUE THREAD

**Issue by RandyHinger** [archetyped/cornerstone#51]
My website crashed today so I deactivated all of my plugins and tried to reactivate them one by one. Whenever I try to reactivate the Cornerstone plugin, my website gets a fatal error and I have go back to the beginning and deactivate all plugins again.
My website URL is https://plazamariachi.com/

**Comment by RandyHinger** [comment]
I reverted to a month old backup of the website and it told me the error was in line 105 of the plugin PHP file. I commented that section of the PHP file to make it inactive and it fixed the problem, at least for now.

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name, as the files being loaded by the plugin at the link provided do not match this Cornerstone plugin. The plugin you are using may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
