### ISSUE TITLE
Cornerstone Error - Failing To Load - Crashing Website

### ISSUE THREAD

**Issue by PrivatePickle** [archetyped/cornerstone#52]
I am suddenly receiving this error:

An error of type E_ERROR was caused in line 40 of the file /home/prpr3311/public_html/wp-content/plugins/cornerstone/includes/classes/Util/IocContainer.php. Error message: Call to undefined method ReflectionParameter::hasType()

I am not sure what this means but it is crashing my site privatepickle.com.au

Please advise what I should do here?

Thanks

**Comment by archetyped** [comment]
Hi, this is the support forum for [the Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name, as the error and file details you provided do not match this plugin. The plugin you are using may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.

**Comment by PrivatePickle** [comment]
Hi, this is where the Themeco Cornerstone plugin brought me to raise the error. I am using Cornerstone as my Wordpress Page Builder. Your link is the plugin I am using. 

I have attached an image of the error. 


<img width="1094" alt="Screen Shot 2021-09-11 at 07 08 05" src="https://user-images.githubusercontent.com/90383336/132926570-74630b58-704b-4bd4-b69d-2941c84fcc40.png">

**Comment by archetyped** [comment]
Unfortunately, we have no control over the links a different plugin uses.  However, as per your screenshot, the author of the plugin you are using is Themeco, not Archetyped.

Clicking on the author's name may provide support options, or as previously-noted, you may also be able to find information on getting support via the site where you downloaded/purchased the plugin.

**Comment by PrivatePickle** [comment]
Ok thanks. Maybe there in lies the issue that it is perhaps looking for the incorrect Cornerstone. I'll get in touch with Themeco.
Note, that when I click into this plugin the author is marked as  archetyped..
<img width="756" alt="Screen Shot 2021-09-11 at 10 26 13" src="https://user-images.githubusercontent.com/90383336/132933191-88982d3a-5ce9-478d-ac52-baad3153c339.png">

**Comment by archetyped** [comment]
Yes, that screenshot is of the Cornerstone plugin from WordPress' Plugin Directory (which was linked to in my initial reply).

Per your previous screenshot, you have a different plugin installed that is using the same name, as other details such as author, version, etc. are different than the details shown from WordPress' Plugin Directory.
