### ISSUE TITLE
Cornerstone not working on managed wordpress

### ISSUE THREAD

**Issue by eb6191** [archetyped/cornerstone#54]
I have installed the cornerstone plugin on my wordpress, it said that the plugin was compatible and it installed and activated successfully, yet I cannot find it anywhere or access it in any way...it's as if it wasn't even installed...why???

**Comment by archetyped** [comment]
Hi, have you taken a look at [Cornerstone's official page on WordPress' plugin directory](https://wordpress.org/plugins/cornerstone/)?  It contains screenshots of where Cornerstone's functionality is added throughout WordPress, as well a link to a more in-depth tutorial on using Cornerstone.

Please let me know if you have any specific questions after reviewing Cornerstone's details, and I would be glad to reopen this ticket and take another look.

Thanks.
