### ISSUE TITLE
Can't edit any page using cornerstone plugin after updating it.

### ISSUE THREAD

**Issue by rightsizeyourhomeau** [archetyped/cornerstone#55]
## Description of Problem

We updated the plugin to version 6.1.4 and have updated X theme to 9.1.4. 

After updating, when trying to edit a page, cornerstone is just reading and not loading all its features. See loom- https://www.loom.com/share/615bb5322050472fb41118d09433e32b

Also, we had to go back to a previous backup because of this issue and after restoring the website - we had this error (https://prnt.sc/Lh9kazAtppP0). We had to deactivate cornerstone plugin because of this error.

## Details

* URL of Page exhibiting problem: https://www.rightsizeyourhome.com.au/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of CNR Installed: 6.1.4
* Other plugins installed:

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name, as the details you provided do not match this plugin (version, functionality, etc.). The plugin may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
