### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by nlhgalmonte** [archetyped/cornerstone#56]
I'm receiving the following error:

Fatal error: Uncaught Error: Call to undefined method ReflectionType::getName() in /home/almon826/public_html/wp-content/plugins/cornerstone/includes/classes/Util/IocContainer.php:55

I have contacted our web host and they did get our website somewhat functional again but all of the coding is now visible, since Cornerstone can't be activated without crashing.  The host said they're unable to help further, since the issue is with the plugin itself.

I read #49 but I don't think my situation is the same.  The FAQ section of the plugin page showed a link to this exact page, only:
 Post your questions/comments at [Cornerstone’s official issue tracker](https://github.com/archetyped/cornerstone/wiki/Support-&-Feedback). 

These are the details of my plugin:

Version: 0.7.8
Author: [Archetyped](http://archetyped.com/)
Last Updated: 4 months ago
Requires WordPress Version: 5.3 or higher
Compatible up to: 5.9.3
Active Installations: 90,000+

* URL of Page exhibiting problem: https://almontehighlandgames.com/
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): I'm using Chrome, not sure what the web host was using

Really hope someone can help me.  Thanks a lot!

**Comment by archetyped** [comment]
Hi, this is the same issue as the other ticket you referenced (#49).  The [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/) does not contain the file referenced in the error message you received (`IocContainer.php`).

The actual plugin you are using may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.

Unfortunately, we do not have any control over the links another plugin developer uses, though I do not know why another developer would include links to this support forum for their plugin.
