### ISSUE TITLE
fatal error when activating to use with themeco wordpress theme

### ISSUE THREAD

**Issue by drorindavis** [archetyped/cornerstone#57]
## Description of Problem

Every time I try to activate Cornerstone to use with my themeco wordpress theme, the plugin won't activate due to 

"Plugin could not be activated because it triggered a fatal error."

![image](https://user-images.githubusercontent.com/111318075/185263021-64032779-7078-4980-8e3d-0a8ffde4c8bd.png) 

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): Chrome
* Version of CNR Installed: 6.1.4
* Other plugins installed: 
 - Akismet Anti-spam
 - contact form 7
 - content dock
 - Envato market
 - font awesome 4 menus
 - go daddy quick setup
 - sucuri security - auditing, malware scanner and hardening
 - welcome to wordpress
 - WPBakery Page Builder
 - WPCode - insert headers, footers, and code snippets

**Comment by archetyped** [comment]
Hi, this is the support forum for [the Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name, as the details you provided do not match this plugin. The plugin you are using may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
