### ISSUE TITLE
cornerstone plug in not compatible with php 7.4

### ISSUE THREAD

**Issue by boardmember** [archetyped/cornerstone#58]
## Description of Problem

I updated my php to 7.4 on my site and now I am getting fatal error. Hosting support telling me Cornerstone plugin is not compatable with 7.4. 

## Details

* Right now, the plugin is disabled and obviously any page built with cornerstone is not displaying properly (see attached screen shot)
* Version of CNR Installed: 7.02

![Capture](https://user-images.githubusercontent.com/121725229/210141977-0241bff7-855f-4321-bf42-b87b12991ea8.PNG)

**Comment by archetyped** [comment]
Hi, this is the support forum for [the Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name, as the details you provided do not match this plugin (such as the version number). The plugin you are using may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
