### ISSUE TITLE
Showing error code on the page

### ISSUE THREAD

**Issue by godsgloryhemp** [archetyped/cornerstone#59]
Hi showing error on the page when i am going to deactivate cornerstone plugins this is what happened.
https://godsglorycbd.com/product/solace/

https://prnt.sc/zwzMW20NfJpd

I think some of this plugins can be one of the issues showing error on the site.

Please advice.

Thank you!

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name, as the details and screenshots you provided do not match this plugin. The plugin may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
