### ISSUE TITLE
I have a Cornerstone plugin conflict...

### ISSUE THREAD

**Issue by inkapix** [archetyped/cornerstone#6]
I have themeco X-theme and they use a plugin called Cornerstone and the Cornerstone you developed won't load properly because it has the same name, how can I install archtyped Cornerstone?

**Comment by archetyped** [comment]
It's unfortunate that they've used a name for the plugin that already exists in WordPress' official plugin directory, so the only option is to rename one of the plugins.

Renaming their plugin would be recommended as renaming the official Cornerstone plugin will stop automatic updates from WordPress.

Find the file in their plugin with the plugin headers and change name in the `Plugin Name` header.  See here for more information on WordPress plugin headers: [WordPress Plugin Handbook: Plugin Headers](https://developer.wordpress.org/plugins/the-basics/header-requirements/ "WordPress Plugin Handbook: Plugin Headers")
