### ISSUE TITLE
my website is down!!!!

### ISSUE THREAD

**Issue by sparoministries** [archetyped/cornerstone#60]
My pages on my website are loading, but there is no content. The pages are either completely blank, or it just shows random code. When I go to the backend and open a page in the cornerstone editor, I also do not see any of the elements. It just shows an error that reads...
"This element could not render because it's definition is missing. You might need to activate a plugin."

Here's some example pages:
https://simplifiedguitar.com/ 
https://simplifiedguitar.com/songlibrary/

I've tried it on chrome and windows explorer and the issue is the same. My paying customers have also reported the problem.
I checked the plugins, and cornerstone is activated. There was an update available, so I updated it to 7.1.2, but the problem is still there.
I have not installed any new plugins since the problem started.
This is the 2nd time in 6 months that my website has experienced a site wide crash due to cornerstone. What is going on??

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory.](https://wordpress.org/plugins/cornerstone/)

It appears that you are using a different plugin that may be using the same name, as the details you provided do not match this plugin (version, etc.). The plugin you are using may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
