### ISSUE TITLE
Cornerstone theme causing critical error on website

### ISSUE THREAD

**Issue by proconconsulting** [archetyped/cornerstone#61]
## Description of Problem

(The Cornerstone Theme is causing critical error on the website. Wordpress and I isolated this to an update with the theme that resulted in an issue with the website sometime in March. This error prevented admin and other access. Currently, the website is displaying theme code on the Home page. I have since made the website private (since a Coming Soon page is not available with the theme). Today. we deactivated the theme until the issue is resolved. Please advise. 

## Details

* URL of Page exhibiting problem: hana-proconjv.com
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): all
* Version of CNR Installed: 
* Cornerstone version: Version 4.0.4 
* Wordpress Version: 6.2
* Other plugins installed: Very few
<img width="1296" alt="Screenshot 2023-05-03 at 12 56 34 PM" src="https://user-images.githubusercontent.com/132486598/235986655-c3915b8f-769a-4158-9a76-33d9798fa2bd.png">
<img width="1296" alt="Screenshot 2023-05-03 at 12 58 00 PM" src="https://user-images.githubusercontent.com/132486598/235986883-145aa4c6-386f-439e-91af-d86f19fa8acf.png">

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name, as the details you provided do not match this plugin (example: the different developer for the Cornerstone plugin in your screenshot). The plugin may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
