### ISSUE TITLE
Cornerstone Plugin Causing Critical Website Error

### ISSUE THREAD

**Issue by MummyOfFour** [archetyped/cornerstone#62]
## Description of Problem

Since updating cornerstone it is causing a critical error. I have tried uninstalling and reinstalling and the same thing happens. Please help.

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of CNR Installed: 
* Other plugins installed:

**Comment by MummyOfFour** [comment]
WordPress version 6.4.1
Active theme: X – Child Theme (version 1.0.0)
Current plugin: Cornerstone (version 7.4.4)
PHP version 7.2.34

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin](https://wordpress.org/plugins/cornerstone/) in WordPress' official plugin directory.

It appears that you are using a different plugin that may be using the same name, as the details you provided do not match this plugin. The plugin may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
