### ISSUE TITLE
Unable to save content: 0

### ISSUE THREAD

**Issue by maskalix** [archetyped/cornerstone#64]
Failed to save Error saving content elements: Unable to save content: 0. Error: Error saving content elements: Unable to save content: 0
    at B4 (app.react18.7.5.2.js?ver=7.5.2:26:1445)
    at async app.react18.7.5.2.js?ver=7.5.2:26:4698
g7 @ app.react18.7.5.2.js?ver=7.5.2:5
app.react18.7.5.2.js?ver=7.5.2:26 Save Error for document: Error saving content elements: Unable to save content: 0

Using latest Wordpress 6.6.1
Cornerstone at latest update.

Help please.

**Comment by maskalix** [comment]
Solved that by removing emojies. But why?

**Comment by archetyped** [comment]
Hi, this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/plugins/cornerstone/).

It appears that you are using a different plugin that may be using the same name, as the details you provided do not match this plugin. The plugin may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.
