### ISSUE TITLE
Editing page.php in theme twenty fifteen

### ISSUE THREAD

**Issue by nightwaxer** [archetyped/cornerstone#7]
Hi,
I have tried every which way to edit the code using the excellent tutorial you provided-

http://archetyped.com/know/how-to-organize-posts-in-sections-in-wordpress-with-cornerstone/?utm_source=twitterfeed&utm_medium=twitter

but have had no luck. Obviously I am doing it wrong, unless the code is different in theme twenty-fifteen. I would like the page (section) to have a paragraph under the title on the page, and Title and Excerpt of the posts displayed (similar to the picture on the tutorial). For example:
Page Title
paragraph about the page
Post Title
Post Excerpt (with read more...)

This is the default code:

![image](https://cloud.githubusercontent.com/assets/14301529/9890343/3dfb8568-5bb4-11e5-93eb-a191388b12fa.png)

Would you be able to provide the exact code and exactly where I am supposed to insert it? Many thanks. -

**Comment by archetyped** [comment]
Hi, I'd be glad to help.  Please post the template code you are using based on the tutorial and I will take a look at what the problem might be.

**Comment by nightwaxer** [comment]
Here it is. The problem is I don't know where to insert it. I've tried several different combinations but none of them work for me. 

<?php if ( cnr_have_children() ) : while ( cnr_have_children() ) : cnr_next_child(); ?>
<h3><?php the_title(); ?></h3>
<div><?php the_excerpt(); ?></div>
<?php endwhile; endif; ?>

**Comment by archetyped** [comment]
Cornerstone's children posts can be output anywhere within the section's own loop.  Here is an example using a modified version of `loop-page.php` from WP's TwentyTen theme:

```php
<?php if ( have_posts() ) while ( have_posts() ) : the_post(); ?>

	<div id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
		<?php if ( is_front_page() ) { ?>
			<h2 class="entry-title"><?php the_title(); ?></h2>
		<?php } else { ?>
			<h1 class="entry-title"><?php the_title(); ?></h1>
		<?php } ?>
	
		<div class="entry-content">
			<?php the_content(); ?>
			<?php wp_link_pages( array( 'before' => '<div class="page-link">' . __( 'Pages:', 'twentyten' ), 'after' => '</div>' ) ); ?>
			<?php edit_post_link( __( 'Edit', 'twentyten' ), '<span class="edit-link">', '</span>' ); ?>
		</div><!-- .entry-content -->
		<div>
		<?php if ( cnr_have_children() ) : while ( cnr_have_children() ) : cnr_next_child(); ?>
			<h3><?php the_title(); ?></h3>
			<div><?php the_excerpt(); ?></div>
		<?php endwhile; endif; ?>
	</div>
	</div><!-- #post-## -->
	<?php cnr_the_feed_links(); ?>
	<?php comments_template( '', true ); ?>

<?php endwhile; // end of the loop. ?>
```
