### ISSUE TITLE
Promo borders

### ISSUE THREAD

**Issue by loganneedy** [archetyped/cornerstone#9]
Here is the link: http://wipeeverytear.org/about/

As you can see, we have a bunch of promo's - I'd like to borders to be the same height and width, or not exist at all. Is there a code I need to put in place in order to do this?

Thank you

**Comment by archetyped** [comment]
Hi, it sounds like you may be referring to a different plugin as Cornerstone does not control the layout of elements on a page. There is usually a link to the plugin's home page on the plugin listing page of your site's admin.
